TRADING_DAYS_PER_YEAR = 252
SHARES_PER_CONTRACT = 100
MATURITY_IN_MONTHS = 3
TRADING_FREQUENCY = 1  # every n days

MATURITY_IN_YEARS = MATURITY_IN_MONTHS / 12

STOCK = "stock.price"
HOLDING = "asset.holding"
OPTONS = "options.value"
DELTA = "options.delta"
TTM = "time.to.maturity"
DONE = "done.flag"

MAX_MINUTES = 60_000
MAX_EPISODES = 50_000

LEAVE_PRINT_EVERY_N_SECS = 120
ERASE_LINE = '\x1b[2K'